# Generated by Django 5.0.4 on 2024-07-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appareil',
            fields=[
                ('s_Generation', models.IntegerField(blank=True, null=True)),
                ('s_GUID', models.CharField(blank=True, max_length=38, null=True, unique=True)),
                ('s_Lineage', models.BinaryField(blank=True, null=True)),
                ('N_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='N° ID')),
                ('DateCreation', models.DateTimeField(auto_now_add=True, null=True)),
                ('Client', models.CharField(max_length=50)),
                ('Opérateur', models.CharField(blank=True, default='Importé', max_length=50, null=True)),
                ('Entretien', models.CharField(max_length=50)),
                ('Destinataire', models.CharField(max_length=50)),
                ('Télésurveillance', models.CharField(blank=True, max_length=50, null=True)),
                ('Adresse', models.CharField(default=' ', max_length=255)),
                ('Code_Postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code Postal')),
                ('Ville', models.CharField(blank=True, max_length=100, null=True)),
                ('Résidence', models.CharField(default=' ', max_length=200)),
                ('Informations', models.CharField(default=' ', max_length=150)),
                ('Code_Client', models.CharField(default=' ', max_length=50)),
                ('Type', models.CharField(blank=True, default='DEFAULT VALUE', max_length=25, null=True)),
                ('MaJFacture', models.BooleanField(default=False)),
                ('Incarcération', models.CharField(blank=True, max_length=50, null=True)),
                ('Code_consigne', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code consigne')),
                ('Consigne_volatile', models.CharField(blank=True, max_length=255, null=True, verbose_name='Consigne volatile')),
                ('Utilisateur', models.CharField(blank=True, max_length=50, null=True)),
                ('Opérateur2', models.CharField(blank=True, max_length=50, null=True)),
                ('dateImport', models.DateTimeField(auto_now_add=True, null=True)),
                ('MES', models.DateTimeField(blank=True, null=True)),
                ('RES', models.DateTimeField(blank=True, null=True)),
                ('Phonie', models.CharField(default=' ', max_length=50)),
                ('Transmetteur', models.CharField(default=' ', max_length=200)),
                ('Autres_1', models.TextField(blank=True, null=True)),
                ('Autres_2', models.TextField(blank=True, null=True)),
                ('Observations', models.CharField(blank=True, max_length=2048, null=True)),
                ('Id_Societe', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Appareils',
                'db_table': 'appareil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MessagesAscenseurs',
            fields=[
                ('N_des_messages', models.AutoField(primary_key=True, serialize=False, verbose_name='N°des messages')),
                ('N_ID', models.IntegerField(blank=True, null=True, verbose_name='N° ID')),
                ('Destinataire', models.CharField(blank=True, max_length=255, null=True)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Message', models.TextField(blank=True, null=True)),
                ('Nom', models.CharField(blank=True, max_length=255, null=True)),
                ('Téléphone', models.CharField(blank=True, max_length=255, null=True)),
                ('Digicode', models.CharField(blank=True, max_length=255, null=True)),
                ('Action', models.TextField(blank=True, null=True)),
                ('Nom_de_l_appelant', models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom de l'appelant")),
                ('Société_de_l_appelant', models.CharField(blank=True, max_length=255, null=True, verbose_name="Société de l'appelant")),
                ('Adresse_de_l_appelant', models.CharField(blank=True, max_length=255, null=True, verbose_name="Adresse de l'appelant")),
                ('Code_postal_de_l_appelant', models.CharField(blank=True, max_length=255, null=True, verbose_name="Code postal de l'appelant")),
                ('Ville_de_l_appelant', models.CharField(blank=True, max_length=255, null=True, verbose_name="Ville de l'appelant")),
                ('Téléphone_de_l_appelant', models.CharField(blank=True, max_length=255, null=True, verbose_name="Téléphone de l'appelant")),
                ('Digicode_de_l_appelant', models.CharField(blank=True, max_length=255, null=True, verbose_name="Digicode de l'appelant")),
                ('Nature_de_l_appel', models.CharField(blank=True, max_length=255, null=True, verbose_name="Nature de l'appel")),
                ('Stocké', models.CharField(blank=True, max_length=255, null=True)),
                ('Incarcération', models.CharField(blank=True, max_length=255, null=True)),
                ('Opérateur', models.CharField(blank=True, max_length=255, null=True)),
                ('Téléphone_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Téléphone 2')),
                ('Confirmation', models.CharField(blank=True, max_length=255, null=True)),
                ('ConfIncar', models.DateTimeField(blank=True, null=True)),
                ('ConfIncar2', models.CharField(blank=True, max_length=255, null=True)),
                ('Commentaires', models.TextField(blank=True, null=True)),
                ('Autres1', models.CharField(blank=True, max_length=255, null=True)),
                ('Autres2', models.CharField(blank=True, max_length=255, null=True)),
                ('Etat', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Message Ascenseur',
                'verbose_name_plural': 'Messages Ascenseurs',
                'db_table': 'messages ascenseurs',
            },
        ),
    ]
