# Generated by Django 4.1 on 2026-01-13 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesclient', '0001_initial'),
    ]

    operations = [
    ]
